#!/usr/bin/env bash
#
#  Licensed to Cloudera, Inc. under one or more contributor license
#  agreements.  See the NOTICE file distributed with this work for
#  additional information regarding copyright ownership.  Cloudera,
#  Inc. licenses this file to you under the Apache License, Version
#  2.0 (the "License"); you may not use this file except in compliance
#  with the License.  You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#

BASEDIR=`dirname ${0}`
BASEDIR=`cd ${BASEDIR}/..;pwd`

HUAHIN_OPTS="-server -Xmx256m -Xms256m -XX:ParallelGCThreads=2 -XX:+UseParNewGC -XX:+UseConcMarkSweepGC"

HUAHIN_PORT=$BASEDIR/conf/port
HUAHIN_SHUTDOWN_PORT=$BASEDIR/conf/shutdownport
HUAHIN_LOG=$BASEDIR/log/huahin-emanager.log
HUAHIN_LIB=$BASEDIR/lib
HUAHIN_WEB=$BASEDIR/webapp

HUAHIN_JAR=`ls $HUAHIN_LIB/huahin-emanager-*.jar`
HUAHIN_PORT=`cat $HUAHIN_PORT`
HUAHIN_SHUTDOWN_PORT=`cat $HUAHIN_SHUTDOWN_PORT`

case $1 in
  start)
    echo "Starting huahin emanager"
    java $HUAHIN_OPTS -Dhuahin.home=$BASEDIR -jar $HUAHIN_JAR start $HUAHIN_WEB $HUAHIN_PORT $HUAHIN_SHUTDOWN_PORT >> $HUAHIN_LOG 2>&1 &
    ;;
  stop)
    echo "Stopping huahin emanager"
    java $HUAHIN_OPTS -Dhuahin.home=$BASEDIR -jar $HUAHIN_JAR stop $HUAHIN_WEB $HUAHIN_PORT $HUAHIN_SHUTDOWN_PORT >> $HUAHIN_LOG 2>&1 &
    ;;
  restart)
    echo "Stopping huahin emanager"
    java $HUAHIN_OPTS -Dhuahin.home=$BASEDIR -jar $HUAHIN_JAR stop $HUAHIN_WEB $HUAHIN_PORT $HUAHIN_SHUTDOWN_PORT >> $HUAHIN_LOG 2>&1 &

    echo "Starting huahin emanager"
    java $HUAHIN_OPTS -Dhuahin.home=$BASEDIR -jar $HUAHIN_JAR start $HUAHIN_WEB $HUAHIN_PORT $HUAHIN_SHUTDOWN_PORT >> $HUAHIN_LOG 2>&1 &
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
    ;;
esac

exit 0

